spring.application.name=Monopoly-gateway

# Port for the API Gateway
server.port=8080

# =========================
# Gateway MVC Route Config
# =========================

# Identity Service
spring.cloud.gateway.mvc.routes[0].id=identity-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/identity/**

# Game Engine Service
spring.cloud.gateway.mvc.routes[1].id=gameengine-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/game-engine/**

# Game Room Service
spring.cloud.gateway.mvc.routes[2].id=gameroom-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8085
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/game-room/**

# Infra Service
spring.cloud.gateway.mvc.routes[3].id=infra-service
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8086
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/infra/**

# Leader Service
spring.cloud.gateway.mvc.routes[4].id=leader-service
spring.cloud.gateway.mvc.routes[4].uri=http://localhost:8087
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/leaderboard/**

# Notification Service
spring.cloud.gateway.mvc.routes[5].id=notification-service
spring.cloud.gateway.mvc.routes[5].uri=http://localhost:8088
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/notifications/**

# Player Service
spring.cloud.gateway.mvc.routes[6].id=player-service
spring.cloud.gateway.mvc.routes[6].uri=http://localhost:8089
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/players/**

# Property Service
spring.cloud.gateway.mvc.routes[7].id=property-service
spring.cloud.gateway.mvc.routes[7].uri=http://localhost:8090
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/properties/**

